name: E2E Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/issues-app/**'
      - 'packages/ui/**'
      - 'apps/e2e/**'
      - '.github/workflows/e2e-tests.yml'
  push:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Build packages
      run: pnpm build
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./apps/e2e
    
    - name: Start development server
      run: |
        pnpm dev &
        sleep 30
        curl -f http://localhost:3000 || exit 1
      timeout-minutes: 5
      
    - name: Run Playwright tests
      run: npx playwright test --reporter=html
      working-directory: ./apps/e2e
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: apps/e2e/playwright-report/
        retention-days: 30

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: apps/e2e/test-results/
        retention-days: 30